# Put defined MCU peripherals here (in alphabetical order)
FEATURES_PROVIDED += periph_gpio periph_gpio_irq
FEATURES_PROVIDED += periph_spi
FEATURES_PROVIDED += periph_timer
FEATURES_PROVIDED += periph_uart
FEATURES_PROVIDED += periph_pm
FEATURES_PROVIDED += periph_cpuid

# The board MPU family (used for grouping by the CI system)
FEATURES_MCU_GROUP = avrxmega6

-include $(RIOTCPU)/atxmega256a3u/Makefile.features
