# export board specific dependencies to the global includes-listing

ifneq (,$(filter netdev_default gnrc_netdev_default,$(USEMODULE)))
  # For support of AT86RF231 SOC devices
  USEMODULE += at86rf231
endif
